coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.config.*"
  - "next.config.ts"
  - "public/**"
  - ".next/**"
  - "node_modules/**"
  - "coverage/**"
  - "playwright-report/**"
  - "e2e-results/**"

flags:
  unit:
    paths:
      - tests/unit/
    carryforward: true
  integration:
    paths:
      - tests/integration/
    carryforward: true
